---
title: "Decreasing Crime Rates in Toronto Does Not Reflect the Increase in Hate Crimes, Racial Injustices and Safety Satisfaction during the Pandemic"
author: 
  - Emily Panus
thanks: "Code and data are available at: https://github.com/panusemi/Final-Toronto-Crime-Pandemic.git."
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "Neighbourhood crime occurring in cities are useful to study as it can concentrate their policies, initiatives, and allocation of police and resources and overall produce a safer environment for citizens. The crime dataset from Open Data Toronto and the General Social Survey of Victimization are used to analyze neighbourhoods that were most affected by crime, how crime rates have changed over the years of 2014-2020 and better understand how Canadians perceive crime, the justice system and on their experiences of victimization. While the number of reported crimes in Toronto have been slowly increasing between the years 2014-2019 with certain neighbourhoods experience higher crime rates, there is a noticeable change in the volume of crime in the early months of the COVID-19 pandemic in 2020 compared to previous years with majority of Canadians being satisfied with their personal safety from crime. However, problems including the under-reporting of certain types of crimes and racial biases causing inaccuracies and biases in results."
keywords: "Crime, Assault, Theft, Shootings, Homicide, Victimization, Neighbourhoods, Police, Safety, Discrimination"
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

\tableofcontents

\listoffigures 

\newpage

# Introduction

Crime is an action of offense that may be prosecuted by the state and is punishable by law and includes the illegal activity of assault, auto theft, break and enter, robbery, homicide and shooting and firearm discharges. Overall, crime rate is the number of crimes done per 100,000 people is calculated by dividing the total number of reported crimes of any kind by the total population, then multiplying the result by 100,000. It is important to monitor crime rates monitors the severity level of police-reported crime in a city and nation to effectively prevent violence and dangerous environments in high crime geographic areas and concentrate policies, funding and proper allocation of police and resources to enhance the quality of life of all citizens. Crime rates are influenced by many factors varying from country to country that include high poverty levels, unemployment, low levels of education are only a few reason crime rates may increase while factors like strict police enforcement and severe sentences may reduce crime rates. 

Canada is a nation known to be one of the safest and peaceful places to live in. In fact, in the 2021 Global Peace Index, Canada ranked in the top 10 most peaceful countries with an overall Global Peace Index (GPI) score of 1.33 (@citeGPI). The GPI quantifies global peacefulness in many nations on a scale of 1 to 5 (5 representing high degree of violence in country) and use it to see and understand the factors that create peace in a society. However, this does not mean that there the nation as a whole is safe and experience low violence.  Many large Metropolitan cities experience high crime. Toronto as Canada’s most populated city experiences higher levels of crime compared to the low levels of the whole country. Studied in this paper is the crime in Toronto and the overall increasing trend the past decade despite the fact that crime rate has decreased about 30% in Canada over the past 20 years (@citecanadacrime), however, the increasing trends of overall crime was distributed in 2020 due to the COVID-19 pandemic. Despite the strict gun laws, there is still much gun violence occurring in Toronto, which also decreased in 2020. However, the pandemic have cause an increase in many more thefts as well as an increase in violent and non-violent hate crimes (@citehatecrime). 


In this paper, we use R (@citeR) to analyze a dataset from opendatatoronto (@citeopendatatoronto) and the General Social Survey – Victimization on neighbourhood crimes of assault, auto theft, break and enter, robbery, homicide and shooting and firearm discharges in Toronto in order to understand the changes of each crime each year as well as monitoring and examining trends in the population’s attitudes and behaviours on violence, crime, and safety in their neighbourhoods to see the structure and functioning of economy based on the views of many different groups of people. Public opinion and satisfaction are an important role when creating a better quality of life for citizens with public policies. The findings using this data presents some implications to them that result in some bias in the results. As previously mentioned, there have been an increase in hate crimes during the COVID-19 pandemic. There is a lot of systematic racial bias when it comes to crime where minorities, particularly people of colour, are overrepresented and are nine times more likely to be stopped and searched by police than white people (@citeracialbias). Careful examination and taking in account for such inequalities must be insured to avoid further injustices and prejudices against people of colour. 

# Data

# Model

# Results

# Discussion

# Appendix

\newpage

# References 

